[versions]
kotlin = "2.1.20"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
# You can define plugin aliases here, for example:
# kotlin-dsl = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[bundles]
# Group related libraries if needed in the future
