name: Gradle Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test on Java 21
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: 🚦 Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: 🔍 Gradle Validation (linting and code style)
        run: ./gradlew check --no-daemon

      - name: 🧹 Clean before build
        run: ./gradlew clean

      - name: 🏗️ Build with Gradle
        run: ./gradlew build --no-daemon

      - name: 📈 Upload test reports if tests fail
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: "**/build/reports/tests/test/"
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: 🛂 Enforce version change
        run: |
          git diff --cached --quiet gradle.properties || echo "✅ Version change detected. Please update the version in gradle.properties." && exit 1