name: Gradle Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test on Java 22
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK 22 with Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22
          cache: gradle

      - name: 📦 Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: 🚦 Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: 🔍 Run linting and validation
        run: ./gradlew check --no-daemon

      - name: 🧹 Clean project
        run: ./gradlew clean --no-daemon

      - name: 🏗️ Build project
        run: ./gradlew build --no-daemon

      - name: 📈 Upload test reports (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: "**/build/reports/tests/test/"
